-- Rolexa internal staff access foundation
-- Run once in the Supabase SQL editor.
-- This creates the private staff membership table and reusable security checks.

create table if not exists public.rolexa_staff_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','employee','analyst')),
  is_active boolean not null default true,
  full_name text,
  job_title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.rolexa_staff_users enable row level security;

-- SECURITY DEFINER avoids recursive RLS checks when policies ask whether
-- the signed-in user is an approved Rolexa staff member.
create or replace function public.is_rolexa_staff(required_roles text[] default null)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.rolexa_staff_users s
    where s.user_id = auth.uid()
      and s.is_active = true
      and (required_roles is null or s.role = any(required_roles))
  );
$$;

revoke all on function public.is_rolexa_staff(text[]) from public;
grant execute on function public.is_rolexa_staff(text[]) to authenticated;

create or replace function public.current_rolexa_staff_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select s.role
  from public.rolexa_staff_users s
  where s.user_id = auth.uid()
    and s.is_active = true
  limit 1;
$$;

revoke all on function public.current_rolexa_staff_role() from public;
grant execute on function public.current_rolexa_staff_role() to authenticated;

-- Staff may see their own membership record.
drop policy if exists "Staff can read own membership" on public.rolexa_staff_users;
create policy "Staff can read own membership"
on public.rolexa_staff_users
for select
to authenticated
using (user_id = auth.uid());

-- Owners and admins may view all staff memberships.
drop policy if exists "Owners and admins can read staff memberships" on public.rolexa_staff_users;
create policy "Owners and admins can read staff memberships"
on public.rolexa_staff_users
for select
to authenticated
using (public.is_rolexa_staff(array['owner','admin']));

-- Only owners can create, change or remove staff access.
drop policy if exists "Owners can create staff memberships" on public.rolexa_staff_users;
create policy "Owners can create staff memberships"
on public.rolexa_staff_users
for insert
to authenticated
with check (public.is_rolexa_staff(array['owner']));

drop policy if exists "Owners can update staff memberships" on public.rolexa_staff_users;
create policy "Owners can update staff memberships"
on public.rolexa_staff_users
for update
to authenticated
using (public.is_rolexa_staff(array['owner']))
with check (public.is_rolexa_staff(array['owner']));

drop policy if exists "Owners can delete staff memberships" on public.rolexa_staff_users;
create policy "Owners can delete staff memberships"
on public.rolexa_staff_users
for delete
to authenticated
using (public.is_rolexa_staff(array['owner']));

-- Internal audit trail. The dashboard can log privileged actions here later.
create table if not exists public.rolexa_admin_audit_log (
  id bigint generated by default as identity primary key,
  staff_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.rolexa_admin_audit_log enable row level security;

drop policy if exists "Internal staff can read audit log" on public.rolexa_admin_audit_log;
create policy "Internal staff can read audit log"
on public.rolexa_admin_audit_log
for select
to authenticated
using (public.is_rolexa_staff(array['owner','admin']));

drop policy if exists "Internal staff can create audit entries" on public.rolexa_admin_audit_log;
create policy "Internal staff can create audit entries"
on public.rolexa_admin_audit_log
for insert
to authenticated
with check (
  staff_user_id = auth.uid()
  and public.is_rolexa_staff(array['owner','admin','employee','analyst'])
);

-- IMPORTANT BOOTSTRAP STEP
-- After running this file, add the first owner using the email address of
-- an existing Supabase Auth user. Replace the placeholder before running it.
--
-- insert into public.rolexa_staff_users (user_id, role, is_active, full_name, job_title)
-- select id, 'owner', true, 'Corum', 'Director'
-- from auth.users
-- where lower(email) = lower('REPLACE_WITH_YOUR_LOGIN_EMAIL')
-- on conflict (user_id) do update set
--   role = excluded.role,
--   is_active = true,
--   full_name = excluded.full_name,
--   job_title = excluded.job_title,
--   updated_at = now();
